---
servers:
  bootstrap.servers: ldndsr000009490.intranet.barcapint.com:9092,ldndsr000009491.intranet.barcapint.com:9092,gbrdsr000012098.intranet.barcapint.com:9092

security:
  security.protocol: PLAINTEXT
  sasl.mechanism: OAUTHBEARER
  ssl.ca.location: /tmp/ifc-certs/CARoot.pem

credentials:
  method: env
  username_variable: BSP_USERNAME
  password_variable: BSP_PASSWORD

bam:
  method: env
  bam_url: BAM_URL
  bam_name: BAM_NAME

producer:
  properties:
    acks: all
    compression.type: gzip
    request.timeout.ms: 40000
    enable.idempotence: True
    retries: 2147483647
    max.in.flight.requests.per.connection: 5

consumer:
  properties:
    error_cb: "@error"
    group.id: GROUP_ID_HERE
    auto.offset.reset: earliest
    enable.auto.commit: !!bool false
