---
servers:
  bootstrap.servers: ldndsr000009480.intranet.barcapint.com:9095,ldndsr000009481.intranet.barcapint.com:9095,gbrdsr000011990.intranet.barcapint.com:9095,gbrdsr000011993.intranet.barcapint.com:9095,gbrdsr000013930.intranet.barcapint.com:9095

security:
  security.protocol: SASL_SSL
  sasl.mechanism: OAUTHBEARER
  ssl.ca.location: /tmp/ifc-certs/CARoot.pem

credentials:
  method: env
  username_variable: BSP_USERNAME
  password_variable: BSP_PASSWORD

bam:
  method: env
  bam_url: BAM_URL
  bam_name: BAM_NAME

producer:
  properties:
    acks: all
    compression.type: gzip
    enable.idempotence: True
    retries: 2147483647
    max.in.flight.requests.per.connection: 5

consumer:
  properties:
    error_cb: "@error"
    group.id: GROUP_ID_HERE
    auto.offset.reset: earliest
    enable.auto.commit: !!bool false
